#!/usr/bin/env bash
#resolving hosts to ip address
echo "127.0.0.2 localhost" | tee -a /etc/hosts > /dev/null
echo "8.8.8.8 facebook.com" | tee -a /etc/hosts > /dev/null
sudo service networking restart

